### PR TITLE
Update pointers to RxJava .16.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
Let's merge this and release 1.1.0?

**Comment by vanniktech** [comment]
I'm still hoping that this library would include the Proguard rules automatically, using `consumerProguardFiles`. Just like proposed here #220 

Since that PR is quite old what are the plans on Proguard and RxAndroid?

**Comment by dlew** [comment]
LGTM

**Pull request merged**
