### PR TITLE
Adding a ReactiveNavigator to handle toActivityForResult in an Observable way

### PR DESCRIPTION
**Pull request by Dorvaryn**
The aim of this component is to handle the navigation to an Activity for result using an Observable and thus avoiding the need to check for result/response code and all the boilerplate code related.

### CODE REVIEW

**Comment by Dorvaryn** [comment]
@hamidp Yes, sorry about the delay I had some family issues and had to tune off from work and OSS stuff for a while.

**Comment by hamidp** [comment]
:+1: Provided we can get some docs on it as well.

**Comment by Dorvaryn** [comment]
@hamidp What type of docs are you thinking of ? I tried to JDoc the code to make it simple enough to understand. There is one more PR adding the rotation handling code and then I have a sample project that presents how to use those tools. I was thinking of adding a doc for usage at that point.

**Comment by hamidp** [comment]
@Dorvaryn More along the lines of a sample readme. 

My :+1: isn't contingent on that -- just would be nice to let consumers of the library know we've got these awesome things.

**Comment by Dorvaryn** [comment]
Should we get this merged in ?

**Pull request closed without merging**
