### PR TITLE
Add plugins helper for modifying schedulers behavior.

### LINKED ISSUE #134: Add Scheduler plugin support
For the main RxJava project there exists [RxJavaSchedulersHook](https://github.com/ReactiveX/RxJava/wiki/Plugins#rxjavaschedulershook), which is great for testing (since you can just set all Schedulers to `immediate()`, even if they would normally be on another thread).

I'd like to propose adding plugin support to RxAndroid as well, starting with support for hooking into `AndroidSchedulers`. There's basically no other way to test it properly, since a lot of the code provided uses `AndroidSchedulers.mainThread()` internally (e.g. `AndroidSubscriptions`). Thoughts?

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #134.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Want to review, @dlew?

**Comment by JakeWharton** [comment]
Could use tests for:

 * `mainThread()` calling through to plugins.
 * `HandlerScheduler` calling through to plugin for action.

**Comment by dlew** [comment]
LGTM :+1:

**Comment by hamidp** [comment]
:+1:

**Comment by hamidp** [comment]
Thanks for taking care of this !

**Comment by JakeWharton** [comment]
Pushed the missing tests. Merging on green.

**Comment by JakeWharton** [comment]
:green_apple: :green_book: :green_heart: :tea: :recycle:

**Pull request merged**
