### PR TITLE
isn't superfluous negative check?

### PR DESCRIPTION
**Pull request by isfaaghyth**

### CODE REVIEW

**Comment by dlew** [comment]
It prevents negative delays from being passed into `Handler`, though one could arguably say that that's superfluous because it looks like `Handler` [prevents negative delays itself](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/Handler.java#598).

**Comment by JakeWharton** [comment]
Didn't I fix this last week?

**Comment by isfaaghyth** [comment]
@dlew noted! thank you, sir.

**Comment by isfaaghyth** [comment]
@JakeWharton this is in scheduleDirect(), sir. 😄

**Comment by JakeWharton** [comment]
Cool. Let's get this merged then!

**Comment by isfaaghyth** [comment]
@JakeWharton thank you, sir

**Pull request merged**
