### PR TITLE
Java 7 support

### PR DESCRIPTION
**Pull request by austynmahoney**
Addresses #37

### CODE REVIEW

**Comment by JakeWharton** [comment]
Need rebase.

**Comment by dlew** [comment]
What's the call on spacing for our gradle files? I found a mix of 2-spaces and 4-spaces when I first started editing and chose to go with 2-spaces.

I honestly couldn't care less which way we go, just want a decision.

**Comment by JakeWharton** [comment]
I would :heart: 2 :heart_eyes:

**Comment by austynmahoney** [comment]
I saw 4 in the files I was looking at, and that is the default IntelliJ and most Android projects are using. I'd vote for that.

**Comment by JakeWharton** [comment]
4 &nbsp; &nbsp;is &nbsp; &nbsp;fine &nbsp; &nbsp;as &nbsp; &nbsp;that's &nbsp; &nbsp;what &nbsp; &nbsp;the &nbsp; &nbsp;source &nbsp; &nbsp;code &nbsp; &nbsp;uses &nbsp; &nbsp;too. &nbsp; &nbsp;I &nbsp; &nbsp;just &nbsp; &nbsp;can't &nbsp; &nbsp;stand &nbsp; &nbsp;how &nbsp; &nbsp;ridiculously &nbsp; &nbsp;far &nbsp; &nbsp;apart &nbsp; &nbsp;everything &nbsp; &nbsp;looks.

**Comment by artem-zinnatullin** [comment]
+1 to 2, but whatever, 1.0.0 is more important than spacing

**Pull request merged**
