### PR TITLE
considers async option in HandlerScheduler.scheduleDirect

### LINKED ISSUE #441: HandlerScheduler.scheduleDirect supports async option?
RxAndroid support async option v2.1.0. now, it support only in `HandlerWorker.schedule`.

I think, `HandlerScheduler.scheduleDirect` should be support async option.
Because, some RxJava operator use `Scheduler.scheduleDirect` method (ex, Maybe.observeOn)

(i prepared source code in https://github.com/ReactiveX/RxAndroid/compare/2.x...satoshun:2.x)

### PR DESCRIPTION
**Pull request by satoshun**
close https://github.com/ReactiveX/RxAndroid/issues/441

### CODE REVIEW

**Comment by JakeWharton** [comment]
This needs tests. Are you able to write them? If not, I can get to it sometime in the next week or two.

**Comment by satoshun** [comment]
oh sorry, i forget writing test...

But, I think already [HandlerSchedulerTest](https://github.com/ReactiveX/RxAndroid/blob/2.x/rxandroid/src/test/java/io/reactivex/android/schedulers/HandlerSchedulerTest.java#L55) is considering the async option test by Parameterized test.

Are there other missing tests? Please tell me if any missing test.

**Comment by JakeWharton** [comment]
Coverage is definitely missing. Either the test should have been failing before without this change or we aren't covering this codepath. Since the test is passing, we have missing coverage on this codepath.

**Comment by ZacSweers** [comment]
The parameterized test just expects no regressions. There weren't any cases added that would have failed the the non-async implementation, as I'm not really sure how to coerce vsync behavior out of robolectric :X

**Comment by JakeWharton** [comment]
You don't need to. We just need to assert the flag is set through all scheduler code paths. There's already a test which asserts that flag is not set on pre-16 which I added.

**Comment by ZacSweers** [comment]
Ah didn't know that was added 😬

**Comment by JakeWharton** [comment]
We just need to add ones which check each scheduler method and assert the flag is set to true on the messages. We should have been doing that anyway...

**Comment by satoshun** [comment]
thx 😄 

> assert the flag is set to true on the messages.

i write a test!

**Comment by satoshun** [comment]
@JakeWharton @hzsweers i added test for async option 😃

**Review by ZacSweers — APPROVED** [review]
Lgtm. Not terribly familiar with those robolectric APIs but not sure of any better ways anyway

**Comment by ZacSweers** [comment]
Thanks!

**Review by jj-crypto — APPROVED** [review]

**Review by AaronWashington — COMMENTED** [review]
[io.reactivex.rxjava3:rxandroid:3.0.0](io.reactivex.rxjava3:rxandroid:3.0.0)

**Pull request merged**
